import Head from "next/head";
import Hero from "../components/hero.js";
import HeroImage from "@/components/heroimage.js";
import Navbar from "@/components/navbar.js";
import AboutMe from "@/components/AboutMe.js";
export default function Home() {
  return (
    <>
      <Head>
        <title>Ali Baloch - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div className="bg-cover h-[100vh] bg-black/80 w-full flex">
        <Navbar />
        <div className="w-1/2">
          <HeroImage />
        </div>
        <div className="flex place-content-start w-1/2 pt-96">
          <Hero />
        </div>
      </div>

      <div>
        <AboutMe />
      </div>
    </>
  );
}
